# Generated by Django 3.2 on 2022-02-05 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.DateTimeField(auto_now_add=True)),
                ('start_parking', models.DateTimeField(auto_now_add=True)),
                ('stop_parking', models.DateTimeField(blank=True, null=True)),
                ('parking_duration', models.DurationField(null=True)),
                ('my_latitude', models.FloatField(null=True)),
                ('my_longitude', models.FloatField(null=True)),
                ('my_geolocation', django_google_maps.fields.GeoLocationField(default=None, max_length=100, null=True)),
                ('my_address', django_google_maps.fields.AddressField(default=None, max_length=200, null=True)),
                ('thumb', models.ImageField(blank=True, default='placeholder-image.png', upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
