# Generated by Django 3.2 on 2022-02-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldfishMemory_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='start_parking',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
