# Generated by Django 3.2 on 2022-02-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldfishMemory_App', '0003_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='parking_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
