# Generated by Django 3.2 on 2022-02-06 16:35

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GoldfishMemory_App', '0004_alter_parkingspot_parking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='my_address',
            field=django_google_maps.fields.AddressField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='my_geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
