# Generated by Django 3.2 on 2022-02-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldfishMemory_App', '0006_alter_parkingspot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='my_latitude',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
