# Generated by Django 3.2 on 2022-02-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoldfishMemory_App', '0007_alter_parkingspot_my_latitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
