# Generated by Django 3.2 on 2022-02-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldfishMemory_App', '0008_delete_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='slug',
            field=models.CharField(editable=False, max_length=30, null=True),
        ),
    ]
