# Generated by Django 3.2 on 2022-02-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoldfishMemory_App', '0010_parkingspot_recording_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'verbose_name_plural': 'Parking Spots DB'},
        ),
    ]
