# Generated by Django 3.2 on 2022-02-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldfishMemory_App', '0011_alter_parkingspot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'ordering': ['start_parking'], 'verbose_name_plural': 'Parking Spots DB'},
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='my_timezone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='slug',
            field=models.CharField(editable=False, max_length=30, null=True, unique=True),
        ),
    ]
