# Generated by Django 3.2 on 2022-02-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldfishMemory_App', '0012_auto_20220217_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='my_latitude',
            field=models.FloatField(null=True),
        ),
    ]
