# Generated by Django 3.2 on 2022-03-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldfishMemory_App', '0014_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
