# Generated by Django 3.2 on 2022-03-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldfishMemory_App', '0015_parkingspot_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cookies_consent',
            field=models.BooleanField(default=False),
        ),
    ]
